### ISSUE TITLE
Zoom charts does not work.

### ISSUE THREAD

**Issue by malyjaponec** [emoncms/emoncms-docker#19]
I have just moved to this docker version of emoncms. Everything seems ok but zoom graphs (really mandatory for power monitoring) are all empty. I have migrated about 4GB of php storage and also complete database into it. If I look at feeds I see updates in SQL feeds. When I look at chart from feed page I can see data updated. But no zoom and simplezoom widget works with these feeds. 

And it looks like this project is dead. I expected that it will move to latest version as soon as possible. And just replacing image of emoncms docker container will give me update. This would be great as I have modified making process so everything about data is outside the containers on the host system. I can delete database image, main image, make it fresh and it runs where it was just before it.

I will investigate this issue more but it is quite slow as I am not linux guru and I do not have 50 hours a day time.

**Comment by TrystanLea** [comment]
We've recently updated the emoncms docker again, if you are still interested / using it, let us know if this is still an issue in the latest version and re-open if needed.
