### ISSUE TITLE
mysql on aarch64?

### ISSUE THREAD

**Issue by karlp** [emoncms/emoncms-docker#20]
I tried with latest too, but no go.  What' missing?

Pulling db (mysql:5.6)...
5.6: Pulling from library/mysql
ERROR: no supported platform found in manifest list
karlp@odroid64:~/src/emoncms-docker$ vi docker-compose.yml 
Pulling db (mysql:latest)...
latest: Pulling from library/mysql
ERROR: no supported platform found in manifest list
karlp@odroid64:~/src/emoncms-docker$

**Comment by beaylott** [comment]
Which odroid are you using?

**Comment by karlp** [comment]
C2.  I just installed it normally as an nginx+letsencrypt+mysql, docker experience wasn't so pleasant unforrunately :)

**Comment by beaylott** [comment]
It looks like the official mysql image only supports amd64 . But the mariadb image supports arm64v8 (which I am guessing is what odroid c2 needs) so you could edit the docker-compose.yml so it uses mariadb. MariaDB 10 is supposed to be compatible with MySQL 5.6 (which is what image currently uses) and should be a drop-in replacement.

If you try it and it works would be grateful for a pull request.
