### ISSUE TITLE
error apache

### ISSUE THREAD

**Issue by tarbax** [emoncms/emoncms-docker#22]
this is the error i get when i try to run the   openenergymonitor/emoncms
system:
intel NUC I3

OS | Resin OS 2.3.0+rev1
Kernel version | 4.8.17-yocto-standard

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Sun Dec 02 12:15:11.689003 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.31 configured -- resuming normal operations
[Sun Dec 02 12:15:11.689029 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by imro2** [comment]
I believe I have received that error when I tried to run the docker image on its own. Have you used docker-compose to start it? Emoncms should run with three containers: web, db and redis.

**Comment by kmlucy** [comment]
~~I have external redis and mysql instances that I am trying to use, so I don't want to use compose. I set the appropriate env variables, but am getting the same logs.~~

I still get these logs, but everything is working. I don't think this is an error.
