### ISSUE TITLE
fatal: Remote branch python3 not found in upstream origin

### ISSUE THREAD

**Issue by oddife** [emoncms/emoncms-docker#34]
Building emonhub
Step 1/7 : FROM python:3.8-slim
 ---> 07ea617545cd
Step 2/7 : ARG EMONHUB_DIR
 ---> Using cache
 ---> f360cdd4fe32
Step 3/7 : RUN apt-get update && apt-get install -y git python3-serial python3-configobj python3-pip
 ---> Using cache
 ---> 33c77f32bd28
Step 4/7 : RUN pip3 install paho-mqtt requests configobj pyserial
 ---> Using cache
 ---> 8af4255a3c62
Step 5/7 : RUN git clone -b python3 https://github.com/openenergymonitor/emonhub.git ${EMONHUB_DIR}
 ---> Running in 5dbd9938e079
Cloning into '/opt/emonhub'...
fatal: Remote branch python3 not found in upstream origin

**Comment by 0raculo** [comment]
Can confirm same issue. Any fix available?

**Comment by TrystanLea** [comment]
This should fix this issue https://github.com/emoncms/emoncms-docker/commit/544a4598bbe4bdd707fc5c42c078a76fcbfd070f

**Comment by oddife** [comment]
Issue solved with above comment by @TrystanLea
