### ISSUE TITLE
Volume for local dev environment point the wrong place

### ISSUE THREAD

**Issue by hallard** [emoncms/emoncms-docker#35]
I just spent a couple of time to understand why changing files on dev environnement just was doing anything. I even thought I was pointing on the wrong server.

There is a bug in documentation and in `docker-compose.override.yml` file

Volumes local mount for dev 

should be 
```
volumes:
  ##mount emoncms files from local FS for dev
  - ./emoncms:/var/www/emoncms
```

and not 
```
volumes:
  ##mount emoncms files from local FS for dev
  - ./emoncms:/var/www/html
```

if it may avoid headaches to other, can't believe I'm the only one using this mode :-)

**Comment by glynhudson** [comment]
Good spot! Thanks a lot for that :+1:
