### ISSUE TITLE
Fixing quick start

### ISSUE THREAD

**Issue by Dave-McCraw** [emoncms/emoncms-docker#39]
If I'm reading it right, the current quick start won't quite work because `./bin/setup_dev_repositories` is not there, so the default mount in `docker-compose.override.yml` leaves Apache with nothing to serve, resulting in 403's.

Not sure which solution is preferable - modify the quick start to set up dev repositories, or modify `docker-compose.override.yml` so this isn't needed. I'll open a PR that just updates the README since that won't impact anyone who is used to the way it currently works.

**Comment by glynhudson** [comment]
Thanks, that's great. I think it's best to have the repositories there. There are various ways to handle this in a production environment but having the repository accessible is useful to get up and running quickly for development.
