### ISSUE TITLE
What branch is the most active/recent?

### ISSUE THREAD

**Issue by sumnerboy12** [emoncms/emoncms-docker#47]
I see there is a `v2` branch with MQTT support - should I be using this? Or is the `master` branch the most up-to-date?

I have got EmonCMS running by building my own image from the `master` branch but MQTT is not working and there is a type on the `devices.git` clone in `Dockerfile` - so unsure if it is actually in-use?

**Comment by sumnerboy12** [comment]
Is anyone maintaining this repo?

**Comment by glynhudson** [comment]
@TrystanLea created the v2 branch, it looks like the most current version. He's away on holiday this week, I'll ask him next week if we can get v2 merged into master.

**Comment by sumnerboy12** [comment]
Thanks @glynhudson. @TrystanLea hope you are having a nice holiday!!

**Comment by sumnerboy12** [comment]
Hey @glynhudson / @TrystanLea - any update on this one?

**Comment by TrystanLea** [comment]
Hello @sumnerboy12 the master branch is currently the most up to date version. We did start exploring some new concepts in v2 but that development got a bit stuck as you can see! We are not currently actively working on the docker side of things but would like to pick it up again when we next get time to spend on it. Our focus is on the emonSD software stack but I do appreciate that it's nice to have a good docker solution as well

**Comment by sumnerboy12** [comment]
Ok cool - thanks for the update. I will close this issue. Thanks for all your great work BTW!!!
