### ISSUE TITLE
docker image for a complete emoncms installation

### ISSUE THREAD

**Issue by alexandrecuer** [emoncms/emoncms-docker#51]
I've tried to run the emoncms-docker. There is a lot of configuration files to manage. Apparently, you have to run the mqtt broker separatly. As I am new to docker, I had difficulties to make it work....

**I wanted to share another way to consider things, with a single image including mariadb, redis, apache and php, totally seamless with the EmonScripts and the emonpi I think**

here is the link to the dockerfile for that :

https://github.com/dromotherm/sandbox/blob/master/emoncms/emoncms_lamp/Dockerfile

and the readme :

https://github.com/dromotherm/sandbox/tree/master/emoncms

To test without having to build or touch any file :
```
docker pull alexjunk/emoncms:0.0.3
docker run --rm -it alexjunk:emoncms:0.0.3
```
To get the container IP address : `docker network inspect bridge`

To send mqtt datas from the host if 172.17.0.2 is the container IP : `mosquitto_pub -h 172.17.0.2 -u "emonpi" -P "emonpimqtt2016" -t 'emon/test/t3' -m 15`

if you want persistant sql and timeseries datas : 
```
docker volume create mariadb_datas
docker volume create ts_datas
docker run --rm -v mariadb_datas:/var/lib/mysql -v ts_datas:/var/opt/emoncms -it alexjunk/emoncms:0.0.3
```
 
everything is working fine : 
- mariadb, redis-server, apache2 and mosquitto are started as services
- the 3 workers : emoncms_mqtt, feedwriter and service-runner are started by supervisord
- sync and backup modules work OK

maybe one can say it is not in the spirit of docker as things are not isolated, etc, etc, but I do think it is in the spirit of emoncms to have its stack mariadb, redis, apache and php in a single container...

@TrystanLea , @chaveiro : any thoughts on that ?

**Comment by FireflyJar** [comment]
I might give this a try, I don't understand much either but I already have a server running couple docker game server and wondering if I should also do emoncms on this machine to track my EVSE.  I saw somewhere in instructions that it's not recommended to put on server with other stuff hosted sharing resources, but I wonder with Docker it would isolate it.

**Comment by alexandrecuer** [comment]
@FireflyJar : it is interesting, I guess EVSE is using MQTT
tell me if you manage to make it work. maybe the multi containers approach (followed by the emoncms-docker github repo) is more suitable because because on the multiservices docker image (the one I propose), the broker right now is not exposed to outside. So it is only accessible on the same network namespace : 
cf https://docs.docker.com/engine/reference/run/#name---name

**Comment by FireflyJar** [comment]
sure will do, not sure what MQTT is,  I have an OpenEVSE https://openevse.dozuki.com/Guide/Services+-+EmonCMS/14?lang=en

Thanks

**Comment by FireflyJar** [comment]
when i do :   docker run --rm -it alexjunk:emoncms:0.0.3
it said:   docker: invalid reference format.

what is --rm and -it ?

**Comment by alexandrecuer** [comment]
`--rm` is to remove after stopping the container
`-it` means interactive, you will see the log in the shell

it is not  `docker run --rm -it alexjunk:emoncms:0.0.3` but  `docker run --rm -it alexjunk/emoncms:0.0.3`

you use linux, mac, windows ? if you are on arm 64 bits you should use the arm image : alexjunk/emoncms:0.0.3.arm64v8
I dont have image for arm 32 bits. On mac, it will work only if the processor is intel 

normally you can do something like that for your mqtt problematic : 
```
docker run --rm -p 8080:80 -p 8883:1883 -it alexjunk/emoncms:0.0.3
```
the output should be : 
```
 * Starting MariaDB database server mysqld                               [ OK ] 
 * Starting Apache httpd web server apache2                                                                             * 
 * Starting network daemon: mosquitto                                                                           [ OK ] 
Starting redis-server: redis-server.
2023-06-22 22:37:34,327 INFO RPC interface 'supervisor' initialized
2023-06-22 22:37:34,328 INFO supervisord started with pid 360
2023-06-22 22:37:35,333 INFO spawned: 'emoncms_mqtt' with pid 371
2023-06-22 22:37:35,339 INFO spawned: 'service-runner' with pid 372
2023-06-22 22:37:35,343 INFO spawned: 'feedwriter' with pid 373
2023-06-22 22:37:36,495 INFO success: emoncms_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-22 22:37:36,495 INFO success: service-runner entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-22 22:37:36,495 INFO success: feedwriter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
you can reach emoncms on http://192.168.1.25:8080 if 192.168.1.25 is the IP address of the host machine

then to publish on the broker : 
```
mosquitto_pub -h 192.168.1.25 -p 8883 -u "emonpi" -P "emonpimqtt2016" -t 'emon/test/t3' -m 15
```
you should see the emoncms inputs list being updated

**Comment by FireflyJar** [comment]
Server is dual Intel Xeon running Linux Mint 21.1

`docker run --rm -p 8080:80 -p 8883:1883 -it alexjunk/emoncms:0.0.3`
worked for me, 

I need to read up on logging in and setting it up, been a while.  and if possible transfer existing data.

Thanks

**Comment by FireflyJar** [comment]
seems to be working, I did find a way to sync the data from emoncms.org,   transferring the data.  
now trying to figure out how to get the apps that emoncms.org has that shows nice report.
![image](https://github.com/emoncms/emoncms-docker/assets/17463234/0ea3f59c-9395-4c84-94c7-d8bb77475bf2)

**Comment by alexandrecuer** [comment]
Nice to hear :-)
If you want to modify as few parameters as possible, use -p 1883:1883 and not -p 8883:1883

**Comment by FireflyJar** [comment]
I played with it and I managed to figure out how to to add the Emoncms App Module
https://github.com/emoncms/app

I see it there but when I click +New, to add an app, it does not show.
